# Configuración de APIs
#RickMorty
api.rickmorty.nom = rickmorty
api.rickmorty.url.character =https://rickandmortyapi.com/api/character
api.rickmorty.url.location =https://rickandmortyapi.com/api/location
api.rickmorty.url.episode  = https://rickandmortyapi.com/api/episode

#Pokemon
api.pokemon.url=https://pokeapi.co/api/v2/pokemon